sentences=["But after Bennigsen's departure, the Grand Duke Tsarevich Constantine Pavlovich joined the army.",
"He failed to acknowledge my departure as I returned to our room.",
"They too beat a hasty departure for the downstairs.",
"Actually, I was considering a departure from my usual costume.",
"He raised the topic as much to take Cynthia's mind off Martha's departure as from any serious concern about the old man.",
"But the countess' health obliged them to delay their departure from day to day.",
"As if it were yesterday I remember the preparations, the departure with my teacher and my mother, the journey, and finally the arrival in Boston.",
"Every plant is constrained to carry Out its functions of germination, growth, nutrition, reproduction, &c., between certain limits of temperature, and somewhere between the extremes of these limits each function finds an optimum temperature at which the working of the living machinery is at its best, and, other things being equal, any great departure from this may induce pathological conditions; and many disasters are due to the failure to provide such suitable temperaturese.g.",
"This new departure she lost no time in proclaiming to the world.",
"She walked towards her quarters, uncertain why his departure bothered her.",
"Betsy remained down in the dumps over Martha's departure but per usual, she successfully researched the Internet and found directions to eight different camping parks in the area.",
"According to Suidas, Plato, on his departure for Sicily, left his pupils in charge of Heraclides.",
"I hurried the preparations for our departure as much as possible, and here we are.",
"This third Late Minoan period - the beginning of which may be fixed about 1400 - is an age of stagnation and decline, but the point of departure continued to be the models supplied by the age that had preceded it.",
"In the confusion of the group's departure, a carload of ice climbers arrived to register.",
"While the old gent's hasty departure was out of character, his rapid exit caused the Deans no concern.",
"But a fortnight after his departure, to the surprise of those around her, she recovered from her mental sickness just as suddenly and became her old self again, but with a change in her moral physiognomy, as a child gets up after a long illness with a changed expression of face.",
"Donald Ryland and Franny Mulligan were checking out this evening, as soon as he returned with Donnie, followed by the Quincy sisters scheduled departure in the morning.",
"Such a break is known as a leaf-gap. A little above the departure of the leaf-bundle the stele again closes up only to be again broken by the departure of the next leaf-bundle.",
"Only a few days after their departure Sir Richard Grenville arrived with supplies and more colonists, fifteen of whom remained when he sailed away.",
"In the few hours remaining before his departure, her head was so far in the clouds that she didn't even notice he said nothing about marriage.",
"Petya, having left his people after their departure from Moscow, joined his regiment and was soon taken as orderly by a general commanding a large guerrilla detachment.",
"Dean felt satisfaction that his wife's dark mood had improved, but Martha's departure remained on her mind.",
"One had her form under my house all winter, separated from me only by the flooring, and she startled me each morning by her hasty departure when I began to stir--thump, thump, thump, striking her head against the floor timbers in her hurry.",
"The old man made a departure from his usual routine in honor of his son's arrival: he gave orders to admit him to his apartments while he dressed for dinner.",
"Moreover, whatever the value of Goethe's labours in that field, they were not published before 1820, long after evolutionism had taken a new departure from the works of Treviranus and Lamarck - the first of its advocates who were equipped for their task with the needful large and accurate knowledge of the phenomena of life as a whole.",
"But while himself remaining, he gave instructions for the departure of the princess and Dessalles with the little prince to Bogucharovo and thence to Moscow.",
"After a sneaky backdoor departure and stop at the variety store for their purchases the couple was on their way.",
"His leave-taking of Andromache in the sixth book of the Iliad, and his departure to meet Achilles for the last time, are most touchingly described.",
"In Dublin, whither he proceeded with Mountjoy, he heard of the accession of King James, at whose court he presented himself in June accompanied by Rory O'Donnell, who had become chief of the O'Donnells after the departure of his brother Hugh Roe.",
"And when after Pierre's departure Helene returned to Petersburg, she was received by all her acquaintances not only cordially, but even with a shade of deference due to her misfortune.",
"In the megaphyllous forms, on the other hand, (Ferns) whose leaves are large relatively to the stem, the departure of the correspondingly large trace causes a gap (leaf-gap) in the vascular cylinder, as already described.",
"A few days before his departure a special thanksgiving, at which Nicholas was present, was held in the cathedral for the Russian victory.",
"The departure left husband Joseph in an even surlier mood than usual, and he growled his way through breakfast.",
"The plane was scheduled to leave in 45 minutes but one look at the departure board was indicative of things to come.",
"Kant had fewer isolated points of departure than intuitionalists; yet gaps and isolation recurred in Kant, and helped to make him the father of modern agnosticism.",
"These commentaries may be described as to a certain extent a new departure in New Testament exegesis.",
"Having repeated her order to Dron to have horses ready for her departure next morning, she went to her room and remained alone with her own thoughts.",
"The news of that battle of Tarutino, unexpectedly received by Napoleon at a review, evoked in him a desire to punish the Russians (Thiers says), and he issued the order for departure which the whole army was demanding.",
"In Proclus we find this conception of an emanation of the world out of the Deity, or the absolute, made more exact, the process being regarded as threefold-0) persistence of cause in effect, (2) the departure of effect from cause, and (3) the tendency of effect to revert to its cause.",
"Inversnaid is the point of arrival and departure for the Trossachs coaches, and here, too, there is a graceful waterfall, fed by the Arklet from the loch of that name, 22 m.",
"The only element of real strength that the statute acquired during the first twenty years of its history came from the Elkins Act of 1903, which stipulated that the published rate should be the legal rate, and declared any departure from the published rate to be a misdemeanour.",
"These in turn converge to a pair of single lines which lead to two groups of marshalling sidings, called ' gridirons ' from their shape, and these again converge to single lines leading to ' lower reception and departure lines ' at the bottom of the slope.",
"This was a departure from the customs of the age, and was perhaps influenced less by generosity than by expediency.",
"By this new departure (19th of October 1781) the Jews were permitted to learn handicrafts, arts and sciences, and with certain restrictions to devote themselves to agriculture.",
"And lastly, the final departure of the great Emperor from his heroic army is presented to us by the historians as something great and characteristic of genius.",
"Princess Mary put off her departure, and for three weeks looked after Natasha as if she had been a sick child.",
"I will confess to you, dear Mary, that in spite of his extreme youth his departure for the army was a great grief to me.",
"Two days after the departure of the Simons the prisoner is said by the Restoration historians to have been put in a dark room which was barricaded like the cage of a wild animal.",
"According to the official returns,' the over-sea immigration for the forty-seven years 1857-1903 aggregated 2,872,588, while the departure of emigrants during the same period was 1,066,480, showing a net addition to the population of 1,806,108.",
"In the principal towns letters may be posted in special boxes at the head office just before the departure of any given mail train, and are conveyed direct to the travelling post office.",
"Until he knew exactly what had happened in Lydia's apartment and the details of Fitzgerald's departure anything was possible.",
"These furrows have apparently been cut in situ with a very accurate engine; for not the slightest departure from parallelism can be detected in any of the movable webs relative to the fixed webs.",
"On his release he had promised he would maintain the treaty of Arras and withdraw from the Netherlands; but he delayed his departure for nearly a year and took part in a punitive campaign against his captors and their allies.",
"Having written this and given the paper to Alpatych, he told him how to arrange for departure of the prince, the princess, his son, and the boy's tutor, and how and where to let him know immediately.",
"The other, from the countess, described their last days in Moscow, their departure, the fire, and the destruction of all their property.",
"In 664 at the synod of Whitby, Oswio accepted the usages of the Roman Church, which led to the departure of Colman and the appointment of Wilfrid as bishop of York.",
"And Prince Andrew after giving directions about his departure went to his room.",
"When later on in his memoirs Count Rostopchin explained his actions at this time, he repeatedly says that he was then actuated by two important considerations: to maintain tranquillity in Moscow and expedite the departure of the inhabitants.",
"After the departure of the Greek troops the Cretan leaders, who had hitherto demanded annexation to Greece, readily acquiesced in the decision of the powers, and the insurgent Assembly, under its president Dr Sphakianakis, a man of good sense and moderation, co-operated with the international commanders in the maintenance of order.",
"After Denisov's departure, Rostov spent another fortnight in Moscow, without going out of the house, waiting for the money his father could not at once raise, and he spent most of his time in the girls' room.",
"During that year after his son's departure, Prince Nicholas Bolkonski's health and temper became much worse.",
"Some days after Anatole's departure Pierre received a note from Prince Andrew, informing him of his arrival and asking him to come to see him.",
"Soon after the duke's departure--before he could possibly have reached Semenovsk--his adjutant came back from him and told Kutuzov that the duke asked for more troops.",
"Owing to the count's customary carelessness nothing was ready for their departure by the twenty-eighth of August and the carts that were to come from their Ryazan and Moscow estates to remove their household belongings did not arrive till the thirtieth.",
"And I'm gone too; again, not in my usual way of departure.",
"Since his departure from Bengal in 1764 the situation of affairs in that settlement had scarcely improved.",
"His approaching departure did not prevent his amusing himself, but rather gave zest to his pleasures.",
"Natasha remained alone and, from the time Princess Mary began making preparations for departure, held aloof from her too.",
"He punished the rebellious clergy severely, and ruled the church with an absolute hand till his departure from England in 1218.",
"It is no ultimate given point of departure; it is due to the reaction of thought upon sensation.",
"The gaps in the outer tubular stele, however, are formed by the departure of aerial branch-traces, instead of leaf-traces as in the ferns.",
"See ' Descent of Ishtar to Hades,' Rev. lines 6-10, where universal non-intercourse of sexes follows Ishtar's departure from earth to Hades.",
"Demeter then returns to Olympus, but before her final departure from earth, in token of her gratitude, she instructs the rulers of Eleusis in the art of agriculture and in the solemnities and rites whereby she desires in future to be honoured.",
"Isolated by the departure of the papal nuncio from Ireland in February 1649, he made overtures for alliance to Ormonde, and afterwards with success to Monck, who had superseded Monro in command of the parliamentarians in the north.",
"- After the departure of Caesar, Antipater warned the adherents of Hyrcanus against taking part in any revolutionary attempts, and his son Herod, who, in spite of his youth, had been appointed governor of Galilee, dealt summarily with Hezekiah, the robber captain who was overrunning the adjacent part of Syria.",
"After the departure of Cassius, Antipater being dead, there was confusion in Judaea.",
"After the field marshal's departure it appears that we are within sight of the enemy and must give battle.",
"Before he left he had a long talk with his father about something, and Princess Mary noticed that before his departure they were dissatisfied with one another.",
"After Metivier's departure the old prince called his daughter in, and the whole weight of his wrath fell on her.",
"The vascular supply of the leaf (leaf-trace) consists of a single strand only in the haplostelic and some of the more primitive siphonostelic forms. In the microphyllous groups Leaf.trace of Pteridophytes (Lycopodiales and Equisetales) in and Petlolar which the leaves are small relatively to the stem, the Strands, single bundle destined for each leaf is a small strand whose departure causes no disturbance in the cauline stele.",
"The countess had fallen asleep and the count, having put off their departure till next morning, went to bed.",
"A friend of the family, Lord Foley, provided the funds for his legal training, and he became a member of Lincoln's Inn on his departure from Oxford, being called to the bar in 1730.",
"I caught MBTA Silver Line to South Station, for my 11:15 departure.",
"I left word I'd call from the airport in the morning and set my phone alarm in time for my early departure.",
"Martha asked, showing the first glimmer of interest since being told of her forced departure.",
"A man, not the usual wimpy social lady, was the culprit who organized the hasty departure.",
"There was no luggage standing by to indicate an imminent departure.",
"There was a loud bang as the front door slammed with Cynthia's violent departure.",
"Yet his help was troubling enough to make her look forward to his departure.",
"Some of his early Mantuan works are in that apartment of the Castello which is termed the Camera degli Sposi - full compositions in fresco, including various portraits of the Gonzaga family, and some figures of genii, &c. In 1488 he went to Rome at the request of Pope Innocent VIII., to paint the frescoes in the chapel of the Belvedere in the Vatican; the marquis of Mantua (Federigo) created him a cavaliere before his departure.",
"They are placed either on the departure side parallel to the platform (' side ' stations) or at right angles to the rails and platforms (' end ' stations).",
"About the same time a visit of Jerome to Aquileia led to a close friendship between the two, and shortly after Jerome's departure for the East Rufinus also was drawn thither (in 372 or 373) by his interest in its theology and monasticism.",
"Many of the inhabitants of the conquered districts, however, still clung to the old connexion, and on the 30th of September 1872 - the day by which the people were required to determine whether they would consider themselves German subjects and remain, or French subjects and transfer their domicile to France-45,000 elected to be still French, and sorrowfully took their departure.",
"In a subject like economics it must always be very difficult to decide how far a departure from the traditional form and.",
"The great canal was not begun; irrigation works were started but were soon given up. The letters of Kleber and Menou (the successors of Bonaparte) show that the expenditure on public works had been so reckless that the colony was virtually bankrupt at the time of Bonaparte's departure; and William Hamilton, who travelled through Egypt in 1802, found few traces, other than military, of the French occupation.",
"Such were his words uttered shortly before his departure from Paris (15th of April).",
"The early castle, which existed before 1086, was important during the civil wars of Stephen's reign; in 1142 Robert, earl of Gloucester, on his departure for France, committed it to his son's charge.",
"Charles's departure from Saxony was delayed for twelve months by a quarrel with the emperor.",
"The importance of this singular but superficial departure from the normal structure has been so needlessly exaggerated as a character that at the present time its value is apt to be unduly depreciated.",
"It is held in high veneration by the Sinhalese, and numerous pilgrims ascend to the sacred spot, where a priest resides to receive their offerings and bless them on their departure.",
"Fixing the 15th of August 1096 as the time for the departure of the crusaders, and Constantinople as the general rendezvous, Urban returned from France to Italy."]

d_sentences=["But after Bennigsen's departure1, the Grand Duke Tsarevich Constantine Pavlovich joined the army.",
"He failed to acknowledge my departure1 as I returned to our room.",
"They too beat a hasty departure1 for the downstairs.",
"Actually, I was considering a departure2 from my usual costume.",
"He raised the topic as much to take Cynthia's mind off Martha's departure1 as from any serious concern about the old man.",
"But the countess' health obliged them to delay their departure1 from day to day.",
"As if it were yesterday I remember the preparations, the departure1 with my teacher and my mother, the journey, and finally the arrival in Boston.",
"Every plant is constrained to carry Out its functions of germination, growth, nutrition, reproduction, &c., between certain limits of temperature, and somewhere between the extremes of these limits each function finds an optimum temperature at which the working of the living machinery is at its best, and, other things being equal, any great departure2 from this may induce pathological conditions; and many disasters are due to the failure to provide such suitable temperaturese.g.",
"This new departure2 she lost no time in proclaiming to the world.",
"She walked towards her quarters, uncertain why his departure1 bothered her.",
"Betsy remained down in the dumps over Martha's departure1 but per usual, she successfully researched the Internet and found directions to eight different camping parks in the area.",
"According to Suidas, Plato, on his departure1 for Sicily, left his pupils in charge of Heraclides.",
"I hurried the preparations for our departure1 as much as possible, and here we are.",
"This third Late Minoan period - the beginning of which may be fixed about 1400 - is an age of stagnation and decline, but the point of departure2 continued to be the models supplied by the age that had preceded it.",
"In the confusion of the group's departure1, a carload of ice climbers arrived to register.",
"While the old gent's hasty departure1 was out of character, his rapid exit caused the Deans no concern.",
"But a fortnight after his departure3, to the surprise of those around her, she recovered from her mental sickness just as suddenly and became her old self again, but with a change in her moral physiognomy, as a child gets up after a long illness with a changed expression of face.",
"Donald Ryland and Franny Mulligan were checking out this evening, as soon as he returned with Donnie, followed by the Quincy sisters scheduled departure1 in the morning.",
"Such a break is known as a leaf-gap. A little above the departure2 of the leaf-bundle the stele again closes up only to be again broken by the departure2 of the next leaf-bundle.",
"Only a few days after their departure1 Sir Richard Grenville arrived with supplies and more colonists, fifteen of whom remained when he sailed away.",
"In the few hours remaining before his departure1, her head was so far in the clouds that she didn't even notice he said nothing about marriage.",
"Petya, having left his people after their departure1 from Moscow, joined his regiment and was soon taken as orderly by a general commanding a large guerrilla detachment.",
"Dean felt satisfaction that his wife's dark mood had improved, but Martha's departure3 remained on her mind.",
"One had her form under my house all winter, separated from me only by the flooring, and she startled me each morning by her hasty departure1 when I began to stir--thump, thump, thump, striking her head against the floor timbers in her hurry.",
"The old man made a departure2 from his usual routine in honor of his son's arrival: he gave orders to admit him to his apartments while he dressed for dinner.",
"Moreover, whatever the value of Goethe's labours in that field, they were not published before 1820, long after evolutionism had taken a new departure2 from the works of Treviranus and Lamarck - the first of its advocates who were equipped for their task with the needful large and accurate knowledge of the phenomena of life as a whole.",
"But while himself remaining, he gave instructions for the departure1 of the princess and Dessalles with the little prince to Bogucharovo and thence to Moscow.",
"After a sneaky backdoor departure1 and stop at the variety store for their purchases the couple was on their way.",
"His leave-taking of Andromache in the sixth book of the Iliad, and his departure1 to meet Achilles for the last time, are most touchingly described.",
"In Dublin, whither he proceeded with Mountjoy, he heard of the accession of King James, at whose court he presented himself in June accompanied by Rory O'Donnell, who had become chief of the O'Donnells after the departure3 of his brother Hugh Roe.",
"And when after Pierre's departure3 Helene returned to Petersburg, she was received by all her acquaintances not only cordially, but even with a shade of deference due to her misfortune.",
"In the megaphyllous forms, on the other hand, (Ferns) whose leaves are large relatively to the stem, the departure2 of the correspondingly large trace causes a gap (leaf-gap) in the vascular cylinder, as already described.",
"A few days before his departure1 a special thanksgiving, at which Nicholas was present, was held in the cathedral for the Russian victory.",
"The departure1 left husband Joseph in an even surlier mood than usual, and he growled his way through breakfast.",
"The plane was scheduled to leave in 45 minutes but one look at the departure1 board was indicative of things to come.",
"Kant had fewer isolated points of departure2 than intuitionalists; yet gaps and isolation recurred in Kant, and helped to make him the father of modern agnosticism.",
"These commentaries may be described as to a certain extent a new departure2 in New Testament exegesis.",
"Having repeated her order to Dron to have horses ready for her departure1 next morning, she went to her room and remained alone with her own thoughts.",
"The news of that battle of Tarutino, unexpectedly received by Napoleon at a review, evoked in him a desire to punish the Russians (Thiers says), and he issued the order for departure1 which the whole army was demanding.",
"In Proclus we find this conception of an emanation of the world out of the Deity, or the absolute, made more exact, the process being regarded as threefold-0) persistence of cause in effect, (2) the departure2 of effect from cause, and (3) the tendency of effect to revert to its cause.",
"Inversnaid is the point of arrival and departure1 for the Trossachs coaches, and here, too, there is a graceful waterfall, fed by the Arklet from the loch of that name, 22 m.",
"The only element of real strength that the statute acquired during the first twenty years of its history came from the Elkins Act of 1903, which stipulated that the published rate should be the legal rate, and declared any departure2 from the published rate to be a misdemeanour.",
"These in turn converge to a pair of single lines which lead to two groups of marshalling sidings, called ' gridirons ' from their shape, and these again converge to single lines leading to ' lower reception and departure1 lines ' at the bottom of the slope.",
"This was a departure2 from the customs of the age, and was perhaps influenced less by generosity than by expediency.",
"By this new departure2 (19th of October 1781) the Jews were permitted to learn handicrafts, arts and sciences, and with certain restrictions to devote themselves to agriculture.",
"And lastly, the final departure1 of the great Emperor from his heroic army is presented to us by the historians as something great and characteristic of genius.",
"Princess Mary put off her departure1, and for three weeks looked after Natasha as if she had been a sick child.",
"I will confess to you, dear Mary, that in spite of his extreme youth his departure1 for the army was a great grief to me.",
"Two days after the departure1 of the Simons the prisoner is said by the Restoration historians to have been put in a dark room which was barricaded like the cage of a wild animal.",
"According to the official returns,' the over-sea immigration for the forty-seven years 1857-1903 aggregated 2,872,588, while the departure1 of emigrants during the same period was 1,066,480, showing a net addition to the population of 1,806,108.",
"In the principal towns letters may be posted in special boxes at the head office just before the departure1 of any given mail train, and are conveyed direct to the travelling post office.",
"Until he knew exactly what had happened in Lydia's apartment and the details of Fitzgerald's departure1 anything was possible.",
"These furrows have apparently been cut in situ with a very accurate engine; for not the slightest departure2 from parallelism can be detected in any of the movable webs relative to the fixed webs.",
"On his release he had promised he would maintain the treaty of Arras and withdraw from the Netherlands; but he delayed his departure1 for nearly a year and took part in a punitive campaign against his captors and their allies.",
"Having written this and given the paper to Alpatych, he told him how to arrange for departure1 of the prince, the princess, his son, and the boy's tutor, and how and where to let him know immediately.",
"The other, from the countess, described their last days in Moscow, their departure1, the fire, and the destruction of all their property.",
"In 664 at the synod of Whitby, Oswio accepted the usages of the Roman Church, which led to the departure1 of Colman and the appointment of Wilfrid as bishop of York.",
"And Prince Andrew after giving directions about his departure1 went to his room.",
"When later on in his memoirs Count Rostopchin explained his actions at this time, he repeatedly says that he was then actuated by two important considerations: to maintain tranquillity in Moscow and expedite the departure1 of the inhabitants.",
"After the departure1 of the Greek troops the Cretan leaders, who had hitherto demanded annexation to Greece, readily acquiesced in the decision of the powers, and the insurgent Assembly, under its president Dr Sphakianakis, a man of good sense and moderation, co-operated with the international commanders in the maintenance of order.",
"After Denisov's departure1, Rostov spent another fortnight in Moscow, without going out of the house, waiting for the money his father could not at once raise, and he spent most of his time in the girls' room.",
"During that year after his son's departure3, Prince Nicholas Bolkonski's health and temper became much worse.",
"Some days after Anatole's departure1 Pierre received a note from Prince Andrew, informing him of his arrival and asking him to come to see him.",
"Soon after the duke's departure1--before he could possibly have reached Semenovsk--his adjutant came back from him and told Kutuzov that the duke asked for more troops.",
"Owing to the count's customary carelessness nothing was ready for their departure1 by the twenty-eighth of August and the carts that were to come from their Ryazan and Moscow estates to remove their household belongings did not arrive till the thirtieth.",
"And I'm gone too; again, not in my usual way of departure1.",
"Since his departure1 from Bengal in 1764 the situation of affairs in that settlement had scarcely improved.",
"His approaching departure3 did not prevent his amusing himself, but rather gave zest to his pleasures.",
"Natasha remained alone and, from the time Princess Mary began making preparations for departure1, held aloof from her too.",
"He punished the rebellious clergy severely, and ruled the church with an absolute hand till his departure1 from England in 1218.",
"It is no ultimate given point of departure2; it is due to the reaction of thought upon sensation.",
"The gaps in the outer tubular stele, however, are formed by the departure2 of aerial branch-traces, instead of leaf-traces as in the ferns.",
"See ' Descent of Ishtar to Hades,' Rev. lines 6-10, where universal non-intercourse of sexes follows Ishtar's departure3 from earth to Hades.",
"Demeter then returns to Olympus, but before her final departure3 from earth, in token of her gratitude, she instructs the rulers of Eleusis in the art of agriculture and in the solemnities and rites whereby she desires in future to be honoured.",
"Isolated by the departure1 of the papal nuncio from Ireland in February 1649, he made overtures for alliance to Ormonde, and afterwards with success to Monck, who had superseded Monro in command of the parliamentarians in the north.",
"- After the departure3 of Caesar, Antipater warned the adherents of Hyrcanus against taking part in any revolutionary attempts, and his son Herod, who, in spite of his youth, had been appointed governor of Galilee, dealt summarily with Hezekiah, the robber captain who was overrunning the adjacent part of Syria.",
"After the departure3 of Cassius, Antipater being dead, there was confusion in Judaea.",
"After the field marshal's departure1 it appears that we are within sight of the enemy and must give battle.",
"Before he left he had a long talk with his father about something, and Princess Mary noticed that before his departure1 they were dissatisfied with one another.",
"After Metivier's departure1 the old prince called his daughter in, and the whole weight of his wrath fell on her.",
"The vascular supply of the leaf (leaf-trace) consists of a single strand only in the haplostelic and some of the more primitive siphonostelic forms. In the microphyllous groups Leaf.trace of Pteridophytes (Lycopodiales and Equisetales) in and Petlolar which the leaves are small relatively to the stem, the Strands, single bundle destined for each leaf is a small strand whose departure2 causes no disturbance in the cauline stele.",
"The countess had fallen asleep and the count, having put off their departure1 till next morning, went to bed.",
"A friend of the family, Lord Foley, provided the funds for his legal training, and he became a member of Lincoln's Inn on his departure1 from Oxford, being called to the bar in 1730.",
"I caught MBTA Silver Line to South Station, for my 11:15 departure1.",
"I left word I'd call from the airport in the morning and set my phone alarm in time for my early departure1.",
"Martha asked, showing the first glimmer of interest since being told of her forced departure1.",
"A man, not the usual wimpy social lady, was the culprit who organized the hasty departure1.",
"There was no luggage standing by to indicate an imminent departure1.",
"There was a loud bang as the front door slammed with Cynthia's violent departure1.",
"Yet his help was troubling enough to make her look forward to his departure1.",
"Some of his early Mantuan works are in that apartment of the Castello which is termed the Camera degli Sposi - full compositions in fresco, including various portraits of the Gonzaga family, and some figures of genii, &c. In 1488 he went to Rome at the request of Pope Innocent VIII., to paint the frescoes in the chapel of the Belvedere in the Vatican; the marquis of Mantua (Federigo) created him a cavaliere before his departure3.",
"They are placed either on the departure1 side parallel to the platform (' side ' stations) or at right angles to the rails and platforms (' end ' stations).",
"About the same time a visit of Jerome to Aquileia led to a close friendship between the two, and shortly after Jerome's departure1 for the East Rufinus also was drawn thither (in 372 or 373) by his interest in its theology and monasticism.",
"Many of the inhabitants of the conquered districts, however, still clung to the old connexion, and on the 30th of September 1872 - the day by which the people were required to determine whether they would consider themselves German subjects and remain, or French subjects and transfer their domicile to France-45,000 elected to be still French, and sorrowfully took their departure1.",
"In a subject like economics it must always be very difficult to decide how far a departure2 from the traditional form and.",
"The great canal was not begun; irrigation works were started but were soon given up. The letters of Kleber and Menou (the successors of Bonaparte) show that the expenditure on public works had been so reckless that the colony was virtually bankrupt at the time of Bonaparte's departure1; and William Hamilton, who travelled through Egypt in 1802, found few traces, other than military, of the French occupation.",
"Such were his words uttered shortly before his departure1 from Paris (15th of April).",
"The early castle, which existed before 1086, was important during the civil wars of Stephen's reign; in 1142 Robert, earl of Gloucester, on his departure1 for France, committed it to his son's charge.",
"Charles's departure1 from Saxony was delayed for twelve months by a quarrel with the emperor.",
"The importance of this singular but superficial departure2 from the normal structure has been so needlessly exaggerated as a character that at the present time its value is apt to be unduly depreciated.",
"It is held in high veneration by the Sinhalese, and numerous pilgrims ascend to the sacred spot, where a priest resides to receive their offerings and bless them on their departure1.",
"Fixing the 15th of August 1096 as the time for the departure1 of the crusaders, and Constantinople as the general rendezvous, Urban returned from France to Italy."]